# Generated by Django 3.2.6 on 2022-02-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=200, unique=True)),
                ('identifier', models.CharField(max_length=200)),
            ],
        ),
    ]
