# Generated by Django 3.2.6 on 2022-02-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Config',
            new_name='ConfigModel',
        ),
    ]
